import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import os from "node:os";
import type { CalendarEntry, CalendarStatus } from "./calendar-shared";

const CALENDAR_FILE = path.join(process.cwd(), ".data", "calendar.json");

// Read-only mirror into Gordon's Obsidian vault so the vault (and Pip)
// stays truthful about the content calendar.
const VAULT_MIRROR = path.join(
  os.homedir(),
  "Documents",
  "Obsidian Vault",
  "APOP Digital",
  "Marketing & socials",
  "Content Calendar (Hub).md"
);

export function loadCalendar(): CalendarEntry[] {
  try {
    return JSON.parse(fs.readFileSync(CALENDAR_FILE, "utf8"));
  } catch {
    return [];
  }
}

function persist(entries: CalendarEntry[]): void {
  fs.mkdirSync(path.dirname(CALENDAR_FILE), { recursive: true });
  fs.writeFileSync(CALENDAR_FILE, JSON.stringify(entries, null, 2));
  try {
    mirrorToVault(entries);
  } catch (err) {
    console.error("[calendar] vault mirror failed:", err);
  }
}

export function createEntry(
  input: Omit<CalendarEntry, "id" | "createdAt" | "updatedAt">
): CalendarEntry {
  const now = new Date().toISOString();
  const entry: CalendarEntry = {
    ...input,
    id: randomUUID().slice(0, 8),
    createdAt: now,
    updatedAt: now,
  };
  const entries = loadCalendar();
  entries.push(entry);
  persist(entries);
  return entry;
}

export function updateEntry(
  id: string,
  patch: Partial<Omit<CalendarEntry, "id" | "createdAt">>
): CalendarEntry | null {
  const entries = loadCalendar();
  const idx = entries.findIndex((e) => e.id === id);
  if (idx === -1) return null;
  entries[idx] = {
    ...entries[idx],
    ...patch,
    id,
    updatedAt: new Date().toISOString(),
  };
  persist(entries);
  return entries[idx];
}

export function deleteEntry(id: string): boolean {
  const entries = loadCalendar();
  const next = entries.filter((e) => e.id !== id);
  if (next.length === entries.length) return false;
  persist(next);
  return true;
}

/** Compact text summary for injection into agent prompts. */
export function calendarSummary(daysBack = 7, daysAhead = 21): string {
  const entries = loadCalendar();
  const from = new Date(Date.now() - daysBack * 86400_000)
    .toISOString()
    .slice(0, 10);
  const to = new Date(Date.now() + daysAhead * 86400_000)
    .toISOString()
    .slice(0, 10);
  const window = entries
    .filter((e) => e.date >= from && e.date <= to)
    .sort((a, b) => a.date.localeCompare(b.date));
  if (window.length === 0) return "Content calendar: empty for this window.";
  return (
    "Content calendar (recent + upcoming):\n" +
    window
      .map(
        (e) =>
          `- ${e.date} [${e.status}] ${e.title}` +
          (e.vertical ? ` (${e.vertical})` : "")
      )
      .join("\n")
  );
}

function mirrorToVault(entries: CalendarEntry[]): void {
  const byMonth = new Map<string, CalendarEntry[]>();
  for (const e of [...entries].sort((a, b) => a.date.localeCompare(b.date))) {
    const month = e.date.slice(0, 7);
    byMonth.set(month, [...(byMonth.get(month) ?? []), e]);
  }
  const icon: Record<CalendarStatus, string> = {
    planned: "🟡",
    scheduled: "🟠",
    posted: "🟢",
  };
  const lines = [
    "---",
    "tags: [marketing-hub, content-calendar, auto-generated]",
    "---",
    "",
    "# Content Calendar (Hub)",
    "",
    "> Auto-generated by the Marketing Hub — do not edit here. Manage it in the Hub (http://localhost:3333 → Calendar).",
    "",
  ];
  for (const [month, monthEntries] of byMonth) {
    lines.push(`## ${month}`, "");
    for (const e of monthEntries) {
      lines.push(
        `- ${icon[e.status]} **${e.date}** — ${e.title}` +
          (e.vertical ? ` _(${e.vertical})_` : "") +
          (e.notes ? ` — ${e.notes}` : "")
      );
    }
    lines.push("");
  }
  fs.writeFileSync(VAULT_MIRROR, lines.join("\n"));
}
